trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    mac:
      imageName: 'macOS-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: |
      echo ">>> Install ooxml-viewer"
      npm install
    displayName: Install

  - bash: |
      echo ">>> Lint ooxml-viewer"
      npm run lint
    displayName: Lint

  - bash: |
      echo ">>> Compile ooxml-viewer"
      npm run compile
    displayName: Build

  - bash: |
      echo ">>> Run integration test"
      npm test
    displayName: Run Tests
    env:
      DISPLAY: ':99.0'
